### ISSUE TITLE
Checklist for the initial 'reinfected' release

### ISSUE THREAD

**Issue by Kaffeine** [InfectionDust/teeworlds-reinfected#1]
First priority:
- Zombies:
  - [ ] Zombies can heal each other with a hammer
  - [ ] Zombies have the correct weapon set
  - [ ] Hunter class
    - [ ] The class has correct skin
    - [ ] A hunter class has two air-jumps
- Humans:
  - [ ] Hero class
    - [ ] The class has correct skin
    - [ ] The hero class has the correct weapons set
- Gameplay features:
  - [ ] Humans become infected on death
  - [ ] The round ends when all players infected
  - [ ] The round ends on time out
    - [ ] Humans win if alive, zombies win otherwise
  - [ ] Class menu
